spring:
  datasource:
    url: jdbc:mysql://reward-calculation-db:3306/reward_calculation_db
    username: root
    password: fkmdbyjdbx383
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect

reward:
  payment:
    api:
      url: http://reward-payment-lb
      port: 8095
