spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/reward_payment_db
    username: root
    password: fkmdbyjdbx383

  datasource:
    url: jdbc:mysql://localhost:3306/reward_payment_db
    username: root
    password: fkmdbyjdbx383
    driver-class-name: com.mysql.cj.jdbc.Driver
