spring:
  # ✅ JDBC для Liquibase
  datasource:
    url: jdbc:h2:mem:reward_payment_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: factor23
    password: factor25

  # ✅ R2DBC для реактивного слоя
  r2dbc:
    url: r2dbc:h2:mem:///reward_payment_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: factor23
    password: factor25

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
