spring:
  r2dbc:
    url: r2dbc:mysql://reward-payment-db:3306/reward_payment_db
    username: root
    password: fkmdbyjdbx383

  datasource:
    url: jdbc:mysql://reward-payment-db:3306/reward_payment_db
    username: root
    password: fkmdbyjdbx383
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: reward-payment-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: java.util.Map
        spring.json.use.type.headers: false
    listener:
      ack-mode: manual
    producer:
      acks: all
      retries: 10
      enable-idempotence: true
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      payments: reward-payment-results