global:
  scrape_interval: 5s  # Collect metrics every 5 seconds
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'reward-calculation-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['reward-calculation-lb:8080']
  - job_name: 'reward-payment-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['reward-payment-lb:8095']